services:
  db:
    image: postgres:14
    container_name: team-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ModelEarthDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./admin/sql/suitecrm-postgres.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: team-api
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    environment:
      SERVER_PORT: 8081
      SERVER_HOST: 0.0.0.0
      COMMONS_HOST: db
      COMMONS_PORT: 5432
      COMMONS_NAME: ModelEarthDB
      COMMONS_USER: postgres
      COMMONS_PASSWORD: postgres
      COMMONS_SSL_MODE: disable
    ports:
      - "8081:8081"
    volumes:
      - ./preferences:/app/preferences     # Excel import
      - ./config:/app/config               # Env/settings
      - ./admin:/app/admin                 # Static files
      - ./wait-for-it.sh:/app/wait-for-it.sh  # DB wait script

volumes:
  pgdata:
